config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  namespace :devise, :path => "/" do
    #Registrations
    post 'sign_up' => 'registrations#create' 

    #Sessions
    get 'login' => 'sessions#new'
    post 'login'  => 'sessions#create'

    
  end

  namespace :admin do
    resources :posts
    patch '/publish' => 'posts#publish_unpublish_post'
  end
  
  get '/index' => 'posts#index'
  

  resources :posts do
    resources :comments
  end

  get '/detail' => 'posts#details'

  get '/all_comments' => 'comments#show_all_comments'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
	belongs_to :user
	
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many  :comments, :dependent => :destroy
	has_one :tag, :dependent => :destroy

	after_create :create_tag

	def create_tag
		Tag.create(name: "View #{self.title} Post",post_id: self.id)
	end
end

app/models/tag.rb
class Tag < ApplicationRecord
	belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, :dependent => :destroy
  has_many :comments, :dependent => :destroy

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :is_admin



	def index
		@posts = Post.all.includes(:comments)
	end

	def new
		@post = current_user.posts.new()
	end

	def create
		@post = current_user.posts.create(post_params)
		if @post.save
			flash[:success] = "Post Created Successfully"
			redirect_to admin_posts_path
		else
			flash[:error] = @post.errors.full_messages.join(', ')
		end
	end
	

	def edit
		@post = Post.find_by(id: params[:id])
	end

	def update
		@post = Post.find_by(id: params[:id])
		if @post.update(post_params)
			flash[:success] = "Post Updated Successfully"
			redirect_to admin_posts_path
		else
			flash[:error] = @post.errors.full_messages.join(', ')
		end
	end

	def destroy
		@post = Post.find_by(id:params[:id])
		@post.destroy		
		flash[:notice] = "Post deleted Successfully"
		@posts = Post.all
	end

	def is_admin
		unless current_user.admin?
      flash[:error] = "You are not authorized to access this page"
		end
	end

  def publish_unpublish_post
  	@post = Post.find_by(id: params[:id])
  	if params[:status] == "unpublish"
  		@post.update(is_published: false)
  	elsif params[:status] == "publish"
  		@post.update(is_published: true)
  	end
  	@posts = Post.all
  end

  

  private
	def post_params
		params.require(:post).permit(:title,:content,:is_published)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  def set_post_value
  	@posts = Post.where(is_published: true).order(created_at: "desc").includes(:comments)
  end
  
  def user_login
   if current_user
     redirect_to index_path
   end
  end


	# protected
	# def after_sign_in_path_for(resource)
 #      new_user_registration_path
 #    end

    # def after_sign_up_path_for(resource)
    #   new_user_session_path(resource)
    # end

    # protected
    # def after_sign_up_path_for(resource)
    #   signed_in_root_path(resource)
    # end

    # def after_update_path_for(resource)
    #   signed_in_root_path(resource)
    # end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_post_value
  before_action :check_user_login  


	def create
		@type = params[:type]
	  @post = Post.find_by(id: params[:post_id])
	  @post.comments.create(text: params[:text], user_id: current_user.id)
	  flash[:notice] = "Your comment is Posted"
	end

	def show_all_comments
	  @post = Post.find_by(id: params[:id]).includes(:comments)
	  @comments = @post.comments.order(created_at: "desc")
	end

    
  def check_user_login
   unless current_user 
     flash[:error]="Please login first."
       redirect_to index_path
   end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post_value
	def index
		@posts = Post.where(is_published: true).order(created_at: "desc").includes(:comments)
	end

	def details
		@post = Post.includes(:comments).find_by(id: params[:id])
	end
  
  def show
		@post = Post.includes(:comments).find_by(id: params[:id])
	end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= form_for [:admin, @post]  do |f| %>
      <% if @post.errors.any? %>
        <div class="panel panel-danger col-md-offset-1">
          <div class="panel-heading">
            <h2 class="panel-title">
              <%= pluralize(@post.errors.count, "error") %>
              prohibited this post from being saved: </h2>
            <div class="panel-body">
              <ul>
                <% @post.errors.full_messages.each do |msg| %>
                  <li>
                    <%= msg %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      <% end %>
        <div class='form-group'>
          <div class='control-label col-md-1'>
            <%= f.label :title %>
          </div>
          <div class='col-md-11'>
            <%= f.text_field :title, class: 'form-control', placeholder: 'Title of post', autofocus: true %>
          </div>
        </div>
        <div class='form-group'>
          <div class='control-label col-md-1'>
            <%= f.label :content %>
          </div>
          <div class='col-md-11'>
            <%= f.text_area :content, rows: 10, class: 'form-control', placeholder: 'Content of post' %>
          </div>
        </div>
        <div class='form-group'>
          <div class='col-md-offset-1 col-md-11'>
            <%= f.submit class: 'btn btn-primary btn-lg pull-right' %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/admin/posts/_posts.html.erb
<% if user_signed_in? %>
  <%= link_to "Create New Post", new_admin_post_path, class: "btn btn-default btn-lg pull-right", id: "new-post-btn" %>
<% end %>
<div class="container">
  <h2>POSTS</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Created At</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
    	<% if @posts.empty? %>
			  <h1 id="no-posts">No Posts Created</h1>
			<% else %>
			
	    <% @posts.each do |post| %>	
	      <tr id="post_<%= post.id %>">
	        <td><%= post.title.capitalize %></td>
	        <td><%= post.created_at.strftime('%d %B, %Y')%></td>
	        <td>
	        <% if post.is_published? %>
	         <%= link_to '<button>Unpublish</button>'.html_safe, admin_publish_path(id: post.id,status: "unpublish"), method: "patch", remote: true%>
	        <% else %>
	          <%= link_to '<button>Publish</button>'.html_safe, admin_publish_path(id: post.id, status: "publish"), method: "patch", remote: true %>
	        <% end %>
	        <%= link_to '<i class="fa fa-pencil" aria-hidden="true"><span class="tooltiptext">Edit</span></i>'.html_safe, edit_admin_post_path(id: post.id)%>
	        <%= link_to '<i class="fa fa-trash" aria-hidden="true"><span class="tooltiptext">Delete</span></i>'.html_safe, admin_post_path(id: post.id), method: :delete, data: { confirm: 'Are you sure?' }, remote: true %>
	        <%= link_to '<i class="fa fa-eye" aria-hidden="true"><span class="tooltiptext">View</span></i>'.html_safe, post_path(id: post.id) if post.is_published? %>
	        </td>
	      </tr>  
	      <% end %> 
	    
	      <%end %>   
     
    </tbody>
  </table>
</div>

app/views/admin/posts/destroy.js.erb
$('#post_<%= @post.id %>').remove();
$('#flash').html("<%= escape_javascript(render :partial => 'shared/flash') %>");

app/views/admin/posts/edit.html.erb
<h3 class="text-center"> Editing Post</h3>

<%= render 'form' %>

app/views/admin/posts/index.html.erb
<div id="posts">
  <%= render partial: "posts" %>
 </div> 

app/views/admin/posts/new.html.erb
<h3 class="text-center"> Adding New Post</h3>

<%= render 'form' %>

app/views/admin/posts/publish_unpublish_post.js.erb
$('#posts').html("<%= escape_javascript(render partial: 'posts')%>")

app/views/comments/_form.html.erb
<%= form_for([post, post.comments.build], class: "form-inline")  do |f| %>
    <div class="form-group">
    	<%= f.text_field :text, placeholder: "Your Comments", class: "form-group" %>
    </div>
    <div class="form-group">
    	<%= f.submit  '<button class="btn btn-default">Add</button>'.html_safe, class: "button is-primary" %>

        
    </div>
<% end %>

app/views/comments/create.js.erb
<% if @type == "index" %>
  $('#comment_update').html("<%= escape_javascript(render partial: 'posts/index_partial')%>");
<% else %>
  $('#comment_update').html("<%= escape_javascript(render partial: 'posts/details_page')%>");
<% end %>

$('#flash').html("<%= escape_javascript(render :partial => 'shared/flash') %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css", media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= render 'shared/flash' %>
  </body>
</html>

app/views/posts/_details_page.html.erb
<div class="detailBox">
    <div class="titleBox">
      <label><%= @post.title%></label>
    </div>
    <div class="commentBox">
      <p class="taskDescription"><%= @post.content%></p>
    </div>
    <div class="actionBox">
        <ul class="commentList">
          <% @post.comments.each do |comment| %>
            <li>
               <%= comment&.user&.email %>
                <div class="commentText">
                    <p class=""><%= comment&.text%></p> <span class="date sub-text">on <%= comment&.created_at&.strftime('%d %B, %Y')%></span>
                    <br/>
                </div>
            </li>
            <% end %>
        </ul>
        <%=link_to "All Comment #{@post.comments.size}", "#"%>
        <%#= render partial: "comments/form"%>
        <%= form_tag(post_comments_path(post_id: @post.id,type: "show"), method: "post", remote: true, class: "form-inline")  do%>
        <%#= hidden_field_tag :post_id, value: post.id %>
          <div class="form-group">
            <%= text_field_tag :text,' ', class: "form-group" %>
          </div>
          <div class="form-group">
            <%= submit_tag  "Add", class: "btn btn-default" %>
          </div>
      <% end %>

    </div>
</div>

app/views/posts/_index_partial.html.erb
<%@posts.each do |post|%>
<div class="detailBox">
    <div class="titleBox">
      <label><%=post.title%></label>
    </div>
    <div class="commentBox">
        
        <p class="taskDescription"><%=post.content%></p>
    </div>
    <div class="actionBox">
        <ul class="commentList">
            <li>
               <%= post&.comments&.last&.user&.email %>
                <div class="commentText">
                    <p class=""><%=post&.comments&.last&.text%></p> <span class="date sub-text">on <%=post&.comments&.last&.created_at&.strftime('%d %B, %Y')%></span>
                    <br/>
                </div>
            </li>
        </ul>
        <%=link_to "All Comment #{post.comments.size}", "#"%>
        <%#= render partial: "comments/form"%>
        <%= form_tag(post_comments_path(post_id: post.id), method: "post", remote: true, class: "form-inline")  do%>
        <%#= hidden_field_tag :post_id, value: post.id %>
          <div class="form-group">
            <%= text_field_tag :text,' ', class: "form-group" %>
          </div>
          <div class="form-group">
            <%= submit_tag  "Add", class: "btn btn-default" %>
          </div>
      <% end %>
      <%= link_to "#{post&.tag&.name}", "#"%>

    </div>
</div>

<%end%>

app/views/posts/details.js.erb
$('#comment_update').html("<%= escape_javascript(render partial: 'posts/details_page')%>");
$('#flash').html("<%= escape_javascript(render :partial => 'shared/flash') %>");

app/views/posts/index.html.erb
<div id="comment_update">
  <%= render partial: "index_partial"%>
</div>

app/views/posts/show.html.erb
<div id="comment_update">
  <%= render partial: "details_page"%>
</div>

app/views/shared/_flash.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div id="flash">
      <% flash.each do |key, message| %>
        <div class="text-center alert alert-<%= key == 'notice'? 'success': 'danger' %>">
          <%= message %>
        </div>
      </div>
      <% end %>
      <%= yield %>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<header role="banner">
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <%= link_to "My Blog App", new_user_registration_path, class: "navbar-brand" %>
     </div>
     <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
       <ul class="nav navbar-nav navbar-right">
         <% if user_signed_in? %>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
         <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Sign in", new_user_session_path %></li>
         <% end %>
         <% if user_signed_in? %>
            <p class="navbar-text">
            Signed in as <%= "#{current_user.email}" %>
            </p>
        <% end %>
       </ul>
     </div>
    </div>
  </nav>
</header>